@baseUrl=http://localhost:3000/api
@resourceName=products
#Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

# @name filterProduct
###
GET {{baseUrl}}/{{resourceName}}?price_gte=200
# @name pagination
###
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=3
###
# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "categoryId": "92b8fb98-0abb-45de-ad9e-5bd4156605aa",
    "name": "Intelligent Frozen Sausages",
    "color": "gold",
    "price": 379,
    "description": "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    "thumbnailUrl": "http://loremflickr.com/640/480"
}

###
# @name update
PATCH  {{baseUrl}}/{{resourceName}}/Q5_304w
Content-Type: application/json

{
    "name": "Intelligent Frozen Sausages update",
    "color": "red",
    "price": 379
}
###
# @name delete
DELETE  {{baseUrl}}/{{resourceName}}/3